[package]
name = "safevalue"
version = "0.1.0"
edition = "2024"
authors = ["Marcel Lambert <marcel_lambert@ymail.com>"]
keywords = ["unsafe", "safe", "utility", "no_std", "derive", "data"]
categories = ["no-std", "rust-patterns"]

[dependencies]


[dev-dependencies]
compiletest_rs = "0.11.0"