blank_lines_lower_bound=0
blank_lines_upper_bound=2
combine_control_expr=false
edition="2024"
style_edition="2024"
enum_discrim_align_threshold = 4
struct_field_align_threshold = 4
format_code_in_doc_comments=true
match_block_trailing_comma=true
max_width=80
imports_granularity="Module"
newline_style="Unix"
reorder_impl_items=true
group_imports="StdExternalCrate"
use_field_init_shorthand=true
use_try_shorthand=true
overflow_delimited_expr=true
fn_single_line=true