name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - run: cargo install cargo-msrv
    - run: cargo msrv verify --output-format json
    - if: ${{ failure() }}
      name: Find MSRV
      run: cargo msrv find --output-format json
